#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

# Autostart hyprlock due to sddm auto login
exec-once = hyprlock

exec-once = hyprpaper
exec-once = blueman-applet

# App Launcher and Backend Elephant
exec-once = elephant & walker --gapplication-service

# Top bar, AGS Widgets & auto hide custom script
exec-once = waybar
exec-once = ags run
exec-once = ~/.config/hypr/scripts/waybar_autohide

# Keyring 
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = bitwarden
exec-once = /usr/lib/hyprland-polkit-agent/hyprland-polkit-agent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Audio mixing (voice + screen)
exec-once = ~/.config/hypr/scripts/combine_audio.sh