# https://wiki.hypr.land/Configuring/Gestures/
gestures {
    gesture = 3, horizontal, scale: 0, workspace, r~1
    workspace_swipe_min_speed_to_force = 0
    workspace_swipe_distance = 50
    workspace_swipe_cancel_ratio = 0.01
    workspace_swipe_create_new = true
    workspace_swipe_use_r = true
}