source = hyprland/modules/animation.conf
source = hyprland/modules/binds.conf
source = hyprland/modules/decoration.conf
source = hyprland/modules/env.conf
source = hyprland/modules/exec.conf
source = hyprland/modules/general.conf
source = hyprland/modules/gesture.conf
source = hyprland/modules/input.conf
source = hyprland/modules/misc.conf
source = hyprland/modules/monitors.conf
source = hyprland/modules/permissions.conf
source = hyprland/modules/rules.conf